- name: Update Linux Hosts
  hosts: all
  become: yes
  tasks:
    - name: Update packages on Debian/Ubuntu systems
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == 'Debian'

    - name: Update packages on Red Hat/CentOS systems
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == 'RedHat'